import { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { WishlistStore } from 'store/wishlist.store';
import styled from 'styled-components';
import { shallow } from 'zustand/shallow';

const Container = styled.div`
  background: #242425;
  padding: 0 2rem;
`;

const MainStyled = styled.main`
  align-items: center;
  color: #fff;
  display: flex;
  flex: 1;
  flex-direction: column;
  justify-content: center;
  margin: 0 auto;
  min-height: 100vh;
  padding: 4rem 0;
  width: 960px;
`;

const Card = styled.a`
  background: #1b1b1b;
  background-clip: border-box;
  border: 1px solid rgba(0, 0, 0, 0.125);
  border-radius: 20px;
  display: flex;
  flex-direction: column;
  gap: 12px;
  margin: 16px 0;
  padding: 16px;
  position: relative;
  word-wrap: break-word;
`;

const Footer = styled.footer`
  align-items: center;
  border-top: 1px solid #eaeaea;
  color: #fff;
  display: flex;
  flex: 1;
  justify-content: center;
  padding: 2rem 0;
`;

const Wishlist: NextPage = () => {
  const [wishlists, removeWishlist] = WishlistStore(
    (state) => [state.wishlists, state.removeWishlist],
    shallow
  );

  const linkToThePlanet = (url: string) => {
    const id = url
      .split('/')
      .filter((item) => item)
      .at(-1);
    const goto = `/planet/${id}`;
    return goto;
  };

  return (
    <Container>
      <Head>
        <title>Star Wars Wishlist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainStyled>
        <h1 className="text-5xl font-bold text-yellow-600">STAR WARS</h1>

        <div className="flex gap-5 text-xl pt-5">
          <Link href="/">Home</Link>
          <h2 className="text-white">Wishlist</h2>
        </div>

        <h5 className="w-full text-2xl py-5">Planets Wishlist</h5>

        <div className="w-full">
          {wishlists.length ? (
            <>
              {wishlists.map((planet, index) => (
                <div key={index}>
                  <Link href={linkToThePlanet(planet.url)} passHref>
                    <Card>
                      <h2 className="text-yellow-500 text-xl">{planet.name}</h2>
                      <p>Population - {planet.population}</p>
                      <p>Terrain - {planet.terrain}</p>
                    </Card>
                  </Link>
                  <button onClick={() => removeWishlist(planet.name)}>remove wishlist</button>
                </div>
              ))}
            </>
          ) : (
            <h1>Wishlist is gone!</h1>
          )}
        </div>
      </MainStyled>

      <Footer>
        <span>Made with ♥ by Dhafa Gustiadi Kurniawan</span>
      </Footer>
    </Container>
  );
};

export default Wishlist;
