import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styled from 'styled-components';
import styles from '../styles/Home.module.css';
import { useFetchInfinitePlanets } from 'hooks/usePlanets';

const Container = styled.div`
  background: #242425;
  padding: 0 2rem;
`;

const MainStyled = styled.main`
  align-items: center;
  color: #fff;
  display: flex;
  flex: 1;
  flex-direction: column;
  justify-content: center;
  min-height: 100vh;
  padding: 4rem 0;
`;

const Footer = styled.footer`
  align-items: center;
  border-top: 1px solid #eaeaea;
  color: #fff;
  display: flex;
  flex: 1;
  justify-content: center;
  padding: 2rem 0;
`;

const Home: NextPage = () => {
  // const { data } = useFetchInfinitePlanets();
  return (
    <Container>
      <Head>
        <title>Star Wars App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainStyled>
        <h1 className="text-5xl font-bold text-yellow-500">STAR WARS</h1>

        {/* <p className={styles.description} test-id="getting started">
          Get started by editing <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href="https://github.com/vercel/next.js/tree/master/examples" className={styles.card}>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
          </a>
        </div> */}
      </MainStyled>

      <Footer>
        <span>Made with ♥ by Dhafa Gustiadi Kurniawan</span>
      </Footer>
    </Container>
  );
};

export default Home;
